version: '3.8'


services:
  agent:
    image: ghcr.io/mikhail-angelov/mcp-excalidraw-agent:latest
    container_name: mcp-excalidraw-agent
    ports:
      - "127.0.0.1:3007:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy-net
    labels:
      monic.enabled: "true"
      monic.check: "http"
      monic.check_http_url: "https://diagram.bconf.com"
      monic.name: "diagram.bconf.com"
      redoproxy.enabled: "true"
      redoproxy.domain: "diagram.bconf.com"
      redoproxy.port: 3000
    command: ["node", "dist/server.js"]


networks:
  proxy-net:
    external: true
